apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejong-item-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sejong-item
  template:    # 파드 라벨 이름
    metadata:
      labels:
        app: sejong-item
    spec:
      containers:
        - name: item
          image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/team4-item:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB-HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-infos
                  key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: sejong-item-service
spec:
  #  ClusterIp는 클러스터 내부에서만 접근가능한 Service를 생성
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080   # 서비스의 포트번호
  selector:
    app: sejong-item







