apiVersion: v1
kind: Service
metadata:
  name: sejong-nginx-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:346903264902:certificate/8d406f49-fb9a-4ef2-a79d-5816c7df219b <<인증서 arn>>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  selector:
    app: sejong-nginx