apiVersion: v1
kind: Service
metadata:
  name: sejong-nginx-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80   # 서비스의 포트번호
  selector:
    app: sejong-nginx